### ISSUE TITLE
Fails if table names contain $

### ISSUE THREAD

**Issue by beiske** [fordfrog/apgdiff#102]
Got the following exception in version 2.4 when trying to compare two schemas:
```
beiske$ apgdiff oracle.sql hibernate.sql 
Exception in thread "main" java.lang.RuntimeException: Cannot find ending semicolon of statement: CREATE TABLE "procedureresult$operation" (
    id bigint NOT NULL,
    name character varying(255),
    result_id bigint
);


-- Remainder of file was included here all the way until:
--
-- PostgreSQL database dump complete
--

	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.getWholeStatement(PgDumpLoader.java:277)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:214)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
	at cz.startnet.utils.pgdiff.Main.main(Main.java:39)
```
My best guess is that it fails to handle the $ in the table name. Both files where created using pg_dump version 9.2.1.

**Comment by DemonVex** [comment]
Fixed by 1c1ddcb
