### ISSUE TITLE
Error when add default value on INHERIT table with field in parent table

### ISSUE THREAD

**Issue by FINDIS** [fordfrog/apgdiff#105]
Bug60.sql 
--------------

```sql
CREATE SEQUENCE ir_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
        
CREATE TABLE ir_actions (
    id integer NOT NULL,
    name character varying(64) DEFAULT ''::character varying NOT NULL,
    type character varying(32) DEFAULT 'window'::character varying NOT NULL,
    usage character varying(32) DEFAULT NULL::character varying,
    create_uid integer,
    create_date timestamp without time zone,
    write_date timestamp without time zone,
    write_uid integer
);


CREATE TABLE ir_act_report_custom (
    report_id integer NOT NULL,
    multi boolean,
    model character varying(64) NOT NULL
)
INHERITS (ir_actions);

ALTER TABLE ONLY ir_act_report_custom ALTER COLUMN id SET DEFAULT nextval('ir_actions_id_seq'::regclass);

ALTER TABLE ONLY ir_act_report_custom ALTER COLUMN name SET DEFAULT ''::character varying;
```

Bug61.sql
--------------

```sql
CREATE SEQUENCE ir_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE ir_actions (
    id integer NOT NULL,
    name character varying(64) DEFAULT ''::character varying NOT NULL,
    type character varying(32) DEFAULT 'window'::character varying NOT NULL,
    usage character varying(32) DEFAULT NULL::character varying,
    create_uid integer,
    create_date timestamp without time zone,
    write_date timestamp without time zone,
    write_uid integer
);


CREATE TABLE ir_act_report_custom (
    report_id integer
)
INHERITS (ir_actions);


ALTER TABLE ONLY ir_act_report_custom ALTER COLUMN id SET DEFAULT nextval('ir_actions_id_seq'::regclass);

ALTER TABLE ONLY ir_act_report_custom ALTER COLUMN name SET DEFAULT ''::character varying;
```

Traceback
--------------

```java
java -jar apgdiff-2.4.jar --ignore-start-with Bug60.sql Bug61.sql
Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot find column 'id' in table 'ir_act_report_custom'
        at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parseAlterColumn(AlterTableParser.java:266)
        at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parse(AlterTableParser.java:79)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:180)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:39)
```

**Comment by DemonVex** [comment]
PR #117
