### ISSUE TITLE
Not support the table with no "id" field ?

### ISSUE THREAD

**Issue by hifly** [fordfrog/apgdiff#106]
Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot find column 'id' in table 'ir_act_client'
        at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parseAlterColumn(AlterTableParser.java:266)
        at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parse(AlterTableParser.java:79)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:180)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

Ubuntu 12.04 pg9.1
apgdiff-2.4 (bin)

Thanks

**Comment by diarmuidcc** [comment]
any news?

**Comment by chadfurman** [comment]
is this still an issue?  @zazabe @diarmuidcc ?  The above post is from 2012 -- what's the problem here?  Same error for everyone?  Could I get a schema to load into a DB and try out which generates this error?

Have you tried building from source?  The master branch?  Develop branch?
