### ISSUE TITLE
Support for ALTER TABLE ... OWNER TO ...

### ISSUE THREAD

**Issue by lathspell** [fordfrog/apgdiff#107]
Hello

The new schema has a table "etl_mobile_delete" which was created by the user "numberman".
Instead of showing the CREATE TABLE and the ALTER TABLE ... OWNER TO, apgdump 2.4 just throws
an exception.

Exception in thread "main" java.lang.RuntimeException: Cannot find object 'public.etl_mobile_delete' for statement 'ALTER TABLE public.etl_mobile_delete OWNER TO numberman;'.
        at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parse(AlterTableParser.java:72)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:180)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:33)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

**Comment by DemonVex** [comment]
Fixed #129
