### ISSUE TITLE
Exception: StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jamienich** [fordfrog/apgdiff#109]
Hi,

I've run the utility and it comes up with the below. Is there any doco on download source, turn on debugging, recompile jar and find issue and ignore lines?  I'll have a quick bash at it.

<code>
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 422
        at java.lang.String.substring(String.java:1934)
        at cz.startnet.utils.pgdiff.parsers.Parser.expect(Parser.java:86)
        at cz.startnet.utils.pgdiff.parsers.Parser.expect(Parser.java:47)
        at cz.startnet.utils.pgdiff.parsers.CreateTableParser.parse(CreateTableParser.java:63)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:178)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:39)
</code>

**Comment by DemonVex** [comment]
Fixed by 1c1ddcb
