### ISSUE TITLE
ALTER TABLE ... ENABLE|DISABLE TRIGGER ... not supported

### ISSUE THREAD

**Issue by fordfrog** [fordfrog/apgdiff#11]
Converted from [SourceForge issue 1746647](http://sourceforge.net/support/tracker.php?aid=1746647), submitted by sareche

Hi, great software... but there is a small bug, I contribute with this log 

Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Don
't know how to parse: DISABLE TRIGGER ALL
        at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parseRows(AlterTabl
eParser.java:195)
        at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parse(AlterTablePar
ser.java:114)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadSchema(PgDumpLoader.
java:173)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadSchema(PgDumpLoader.
java:222)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:36)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:34)

**Comment by jalissonmello** [comment]
Hi,
If possible test the develop branch with the PR #234
