### ISSUE TITLE
Exception in thread "main" java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kpk-in** [fordfrog/apgdiff#121]
When I tried the tool for the first time, I am getting the following error:

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -13
    at java.lang.String.substring(Unknown Source)
    at cz.startnet.utils.pgdiff.parsers.Parser.parseIdentifierInternal(Parser.java:155)
    at cz.startnet.utils.pgdiff.parsers.Parser.parseIdentifier(Parser.java:133)
    at cz.startnet.utils.pgdiff.parsers.CreateIndexParser.parse(CreateIndexParser.java:38)
    at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:188)
    at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
    at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:33)
    at cz.startnet.utils.pgdiff.Main.main(Main.java:39)
```

When I tried it with the online tool too, no output is generated.
It may be some problem with the dump-files created? (I was trying to attach the files server.sql and local.sql, but github does not allow it... )
I am using postgresql 9.1 on windows.
Should I provide any more info?

regards
kpk

**Comment by Ghoughpteighbteau** [comment]
arg. I'm in a distressing situation and I just hit this. I see this error popping up for APGDIFF in other circumstances, I'm guessing it's hitting a keyword it doesn't recognize? Besides the the bug itself, this error maybe could use some polish?
