### ISSUE TITLE
Erro in "Cannot find ending semicolon of statement"

### ISSUE THREAD

**Issue by dioubernardo** [fordfrog/apgdiff#139]
The name of my FK has a $ in their name

ALTER TABLE ONLY tipos_operacoes
    ADD CONSTRAINT "$1" FOREIGN KEY (id_sistema) REFERENCES sistemas(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

Exception in thread "main" java.lang.RuntimeException: Cannot find ending semicolon of statement: ....

	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.getWholeStatement(PgDumpLoader.java:277)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:214)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
	at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

**Comment by gici** [comment]
Hi,
I have the identical issue with my postgres 8.4 db.

:-(

**Comment by DemonVex** [comment]
Fixed by 1c1ddcb
