### ISSUE TITLE
Unable to handle UNLOGGED TABLE

### ISSUE THREAD

**Issue by MaxHofer** [fordfrog/apgdiff#142]
apgdiff silently ignores UNLOGGED tables.
```
-- old.sql
CREATE UNLOGGED TABLE test (
    id integer,
    data varchar(20)
);

-- new.sql
CREATE UNLOGGED TABLE test (
    id integer,
    data varchar(20),
    new_attribute varchar(10)
);
```
`java -jar apgdiff-2.3.jar old.sql new.sql` shows no output. 

On a more complex file (with schemas, tables more complex) apgdiff exits with following error message (```awdb.iia_provision``` was the first unlogged table in the DDL file):
```
Exception in thread "main" java.lang.RuntimeException: Cannot find object 'awdb.iia_provision' for statement 'ALTER TABLE awdb.iia_provision OWNER TO etl;'.
        at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parse(AlterTableParser.java:78)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:179)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:239)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:36)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:45)
```
In both cases the exit code of apgdiff is 0.

**Comment by hufersil** [comment]
Any update on this?
