### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by spficklin** [fordfrog/apgdiff#168]
When using apgdiff I get the following error:

Exception in thread "main" java.lang.NullPointerException
	at cz.startnet.utils.pgdiff.parsers.CommentParser.parseIndex(CommentParser.java:144)
	at cz.startnet.utils.pgdiff.parsers.CommentParser.parse(CommentParser.java:50)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:200)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
	at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

I'm using apgdiff version 2.4 which was installed using apt-get on Ubuntu 14.04 LTS. I've also tried the current binary available for download and I receive the same error.  My version of PostgreSQL is 9.3.9.

Thanks for any help.

**Comment by chadfurman** [comment]
I have a similar issue in Ubuntu 17.04 version 2.4

**Comment by ivoras** [comment]
Same, in 2018.
Don't think apgdiff is usable anymore :(
