### ISSUE TITLE
ParserException: Cannot parse string

### ISSUE THREAD

**Issue by gvasquez-waypoint** [fordfrog/apgdiff#169]
Seem either there is a bug somewhere in apgdiff, or I’m using it the wrong way as I’m getting the following error:

```Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot parse string: CREATE TABLE geo_area_imei_alerta (
    geo_area_id bigint NOT NULL,
    imei bigint NOT NULL,
    destino character varying(150) NOT NULL,
    alert_in boolean DEFAULT false,
    alert_out boolean DEFAULT false,
    estado_anterior boolean DEFAULT false,
    last_time timestamp without time zone,
    enable_dow boolean[] DEFAULT ARRAY[true, true, true, true, true, true, true],
    enable_hour boolean[] DEFAULT ARRAY[true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    id bigint NOT NULL,
    tipo integer DEFAULT 0 NOT NULL
);
Expected expression at position 349 ', true, true, true, '
	at cz.startnet.utils.pgdiff.parsers.Parser.getExpression(Parser.java:319)
	at cz.startnet.utils.pgdiff.parsers.CreateTableParser.parseColumn(CreateTableParser.java:136)
	at cz.startnet.utils.pgdiff.parsers.CreateTableParser.parse(CreateTableParser.java:57)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:178)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
	at cz.startnet.utils.pgdiff.Main.main(Main.java:39)```


I’m using apgdiff v2.4 in OSX, installed vía brew.

**Comment by Stratus3D** [comment]
I am using apgdiff v2.4 jar on OSX 10.10.5 and I am getting a similar error due issue #141. I my guess is something in your SQL isn't being parsed due to lack of support in apgdiff or a syntax error.
