### ISSUE TITLE
PgDumpLoader::stripComment fails when string contains */

### ISSUE THREAD

**Issue by noahwh** [fordfrog/apgdiff#188]
This will crash
```

CREATE TABLE test
(
	test	TEXT  DEFAULT '*/'
);
```

With this stack
```

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.replace(Unknown Source)
	at java.lang.StringBuilder.replace(Unknown Source)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.stripComment(PgDumpLoader.java:365)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.getWholeStatement(PgDumpLoader.java:318)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:184)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:259)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:35)
	at cz.startnet.utils.pgdiff.Main.main(Main.java:39)
```

**Comment by DemonVex** [comment]
Fixed

**Comment by noahwh** [comment]
Much appreciated, thanks for your work on this project.
