### ISSUE TITLE
schema_updates - exception

### ISSUE THREAD

**Issue by athenka** [fordfrog/apgdiff#190]
Comparing './callrec_1.dump.sql' with './callrec_2.dump.sql' .... Exception in thread "main" java.lang.RuntimeException: Cannot find object '"SCHEMA_UPDATES"' for statement 'ALTER TABLE ONLY "SCHEMA_UPDATES" ADD CONSTRAINT "SCHEMA_UPDATES_pk" PRIMARY KEY (version);'.
	at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parse(AlterTableParser.java:78)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:179)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:239)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:36)
	at cz.startnet.utils.pgdiff.Main.main(Main.java:45)

version: apgdiff-2.4.jar

please let me know if you need any additional information.

**Comment by fordfrog** [comment]
my guess is that you are attempting to modify table that either does not have CREATE TABLE statement in the file above this statement or that the table has CREATE TABLE statement but in different schema.
