### ISSUE TITLE
ParserException

### ISSUE THREAD

**Issue by e016510** [fordfrog/apgdiff#191]
$ java -jar apgdiff-2.4.jar --ignore-start-with ./pgdb_tcdm1s.sql ./wwt_test.sql
Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot parse string: CREATE TRIGGER trg_cnsmr_promo_dtl BEFORE UPDATE ON cnsmr_promo_dtl FOR EACH ROW  $trigger$BEGIN :new.RPLCTN_UPDT_TS := systimestamp; END$trigger$
 ;
Expected EXECUTE at position 83 '$trigger$BEGIN :new.'
        at cz.startnet.utils.pgdiff.parsers.Parser.expect(Parser.java:86)
        at cz.startnet.utils.pgdiff.parsers.Parser.expect(Parser.java:47)
        at cz.startnet.utils.pgdiff.parsers.CreateTriggerParser.parse(CreateTriggerParser.java:95)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:195)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

**Comment by jalissonmello** [comment]
Test with this jar
[diff.zip](https://github.com/fordfrog/apgdiff/files/2612346/diff.zip)
