### ISSUE TITLE
Cannot find column of inherited table

### ISSUE THREAD

**Issue by olilau** [fordfrog/apgdiff#205]
apgdiff raises an exception when diffing schema having inherited tables.
apgdiff version is: 2.4

Command used:
  apgdiff ir_actions.6.schema.sql ir_actions.8.schema.sql

Exception:

> Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot find column 'id' in table 'ir_act_report_custom'
>         at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parseAlterColumn(AlterTableParser.java:266)
>         at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parse(AlterTableParser.java:79)
>         at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:180)
>         at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
>         at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
>         at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

ir_actions.6.schema.sql:
  http://pastebin.com/ubUyXpWW

ir_actions.8.schema.sql:
  http://pastebin.com/V8zSAwDY

Thanks.

**Comment by ckremser** [comment]
`java -jar apgdiff-2.4.jar /usr/local/db_dumps/db1.sql /usr/local/db_dumps/db2.sql >> /usr/local/db_dumps/output.sql
Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot find column 'created_by' in table 'academic_plan'
	at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parseAlterColumn(AlterTableParser.java:266)
	at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parse(AlterTableParser.java:79)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:180)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
	at cz.startnet.utils.pgdiff.Main.main(Main.java:39)`
