### ISSUE TITLE
ALTER SEQUENCE OWNER TO not supported

### ISSUE THREAD

**Issue by trinni** [fordfrog/apgdiff#208]
```Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot parse string: ALTER SEQUENCE mySchema.mySeq_pk_autoincrement OWNER TO someUser;
Unsupported command at position 47 'OWNER TO someUser;'
	at cz.startnet.utils.pgdiff.parsers.Parser.throwUnsupportedCommand(Parser.java:402)
	at cz.startnet.utils.pgdiff.parsers.AlterSequenceParser.parse(AlterSequenceParser.java:64)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:219)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:277)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java```

**Comment by chadfurman** [comment]
@trinni maybe https://github.com/fordfrog/apgdiff/pull/211 will help -- let me know if you need a jar

**Comment by ukehartmann** [comment]
@fordfrog / @chadfurman could we do a new release?

**Comment by ama-hlx** [comment]
@chadfurman Running into this issue. Would it be possible for you to share the jar with #211 changes, please?
