### ISSUE TITLE
Problem generating difference

### ISSUE THREAD

**Issue by elidorio** [fordfrog/apgdiff#239]
When comparing 2 database is generating errors, as below:

Tested with release apgdiff-2.5.0-SNAPSHOT.jar

sql commands:
pg_dump -s -U postgres -h 192.168.56.102 -f /home/lidorio/tmp/diff/old.sql xx_us_atual
pg_dump -s -U postgres -h 192.168.56.102 -f /home/lidorio/tmp/diff/new.sql xx_u_2017
J:\diff_new>java -jar apgdiff.jar old.sql new.sql > script_atualizacao.sql
Exception in thread "main" java.lang.NullPointerException
        at cz.startnet.utils.pgdiff.parsers.CommentParser.parseColumn(CommentParser.java:244)
        at cz.startnet.utils.pgdiff.parsers.CommentParser.parse(CommentParser.java:34)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:215)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:259)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:35)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

[diff.zip](https://github.com/fordfrog/apgdiff/files/2152335/diff.zip)

**Comment by elidorio** [comment]
I am using release apgdiff 2.5.0-alpha.2

**Comment by jalissonmello** [comment]
Test with this jar. Generated with PRs:240,236,234,228
[diff.zip](https://github.com/fordfrog/apgdiff/files/2309869/diff.zip)

**Comment by elidorio** [comment]
Worked perfectly. Thank you very much.
Where I can be downloading always the last updated version.

**Comment by jalissonmello** [comment]
Now in release the folder its the jar version 2.6.0

**Comment by ad-pro** [comment]
Similar problem with 2.5.0-snapshot, and with 2.6.0	

at cz.startnet.utils.pgdiff.PgDiffTriggers.getEnablerOrDisableTriggers(PgDiffTriggers.java:222)
	at cz.startnet.utils.pgdiff.PgDiffTriggers.disableOrEnableTriggers(PgDiffTriggers.java:256)
	at cz.startnet.utils.pgdiff.PgDiff.updateSchemas(PgDiff.java:321)
	at cz.startnet.utils.pgdiff.PgDiff.diffDatabaseSchemas(PgDiff.java:144)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:46)
	at cz.startnet.utils.pgdiff.Main.main(Main.java:39)
