### ISSUE TITLE
add support for parsing PARTITIONED BY LIST statements in CREATE TABLE

### ISSUE THREAD

**Issue by saswata248** [fordfrog/apgdiff#274]
Unsupported command at position 396 'PARTITION BY LIST (f'
        at cz.startnet.utils.pgdiff.parsers.Parser.throwUnsupportedCommand(Parser.java:390)
        at cz.startnet.utils.pgdiff.parsers.CreateTableParser.parse(CreateTableParser.java:84)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:178)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:236)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:29)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

**Comment by XavierTolza** [comment]
+1

**Comment by jalissonmello** [comment]
Can you help testing ? There is 2.6.1 jar on https://github.com/jalissonmello/apgdiff/tree/develop/releases

Maybe your problem was resolved.
