### ISSUE TITLE
Unsupported command at position 30 'ATTACH PARTITION raw' -- apgdiff version 2.7.0

### ISSUE THREAD

**Issue by gintaraskuc** [fordfrog/apgdiff#287]
Some issues with version 2.7.0

Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot parse string: ALTER TABLE ONLY raw.aiw_hub ATTACH PARTITION raw.aiw_hub_am FOR VALUES IN ('AM');
Unsupported command at position 30 'ATTACH PARTITION raw'
	at cz.startnet.utils.pgdiff.parsers.Parser.throwUnsupportedCommand(Parser.java:413)
	at cz.startnet.utils.pgdiff.parsers.AlterRelationParser.parse(AlterRelationParser.java:119)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:248)
	at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:322)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:35)
	at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

**Comment by maltebrun** [comment]
Hello,
I'm trying to use apgdiff to compare 2 dumps generated with pg_dump from PostgreSQL 10.

One of the tables is partitionned by values.

apgdiff throw this exception :

Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot parse string: ALTER TABLE ONLY public.mytable_partitionned ATTACH PARTITION public.mytable_2013_t1 FOR VALUES IN ('2013-01', '2013-02', '2013-03');
Unsupported command at position 51 'ATTACH PARTITION pub'
        at cz.startnet.utils.pgdiff.parsers.Parser.throwUnsupportedCommand(Parser.java:413)
        at cz.startnet.utils.pgdiff.parsers.AlterRelationParser.parse(AlterRelationParser.java:119)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:248)
        at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:322)
        at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:35)
        at cz.startnet.utils.pgdiff.Main.main(Main.java:39)

Any help would by appreciated.

**Comment by kamal140415** [comment]
@gintaraskuc I am also facing the same issue. Have you found any work around or solution for this issue?
