### ISSUE TITLE
apgdiff does not support setting comment on inherited column

### ISSUE THREAD

**Issue by fordfrog** [fordfrog/apgdiff#57]
Converted from [SourceForge issue 3133011](http://sourceforge.net/support/tracker.php?aid=3133011), submitted by None

java -jar apgdiff-2.3.jar tmp/r1 tmp/r2 
Exception in thread "main" java.lang.NullPointerException
at cz.startnet.utils.pgdiff.parsers.CommentParser.parseColumn(CommentParser.java:272)
at cz.startnet.utils.pgdiff.parsers.CommentParser.parse(CommentParser.java:46)
at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:202)
at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:239)
at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:36)
at cz.startnet.utils.pgdiff.Main.main(Main.java:45)

**Comment by DemonVex** [comment]
PR #117
