### ISSUE TITLE
Inherited default value issue

### ISSUE THREAD

**Issue by fordfrog** [fordfrog/apgdiff#71]
Converted from [SourceForge issue 3511948](http://sourceforge.net/support/tracker.php?aid=3511948), submitted by None

When a table have inherits columns with default value, pg_dump creates ALTER instructions to set the default values on the child table, even if it has been set only on the parent table. apgdiff doesn't support these instructions and an exception is raised.

Here are the instructions I used to create the tables:

CREATE TABLE parent (name varchar, testbol boolean DEFAULT true);
CREATE TABLE child (age integer) INHERITS (parent);

The attached file, dump_testapg.sql,  contains the dump made with pg_dump (scheme only).

The bug can be easily reproduced by comparing this dump with itself:

apgdiff dump_testapg.sql dump_testapg.sql

Here's the output:

Exception in thread "main" cz.startnet.utils.pgdiff.parsers.ParserException: Cannot parse ALTER TABLE 'child', line 'ALTER COLUMN testbol SET DEFAULT true'
at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parseRows(AlterTableParser.java:171)
at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parse(AlterTableParser.java:99)
at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:176)
at cz.startnet.utils.pgdiff.loader.PgDumpLoader.loadDatabaseSchema(PgDumpLoader.java:224)
at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:32)
at cz.startnet.utils.pgdiff.Main.main(Main.java:39)
Caused by: cz.startnet.utils.pgdiff.parsers.ParserException: Cannot find column 'testbol 'in table 'child'
at cz.startnet.utils.pgdiff.parsers.AlterTableParser.parseRows(AlterTableParser.java:162)
... 5 more

This was tested with versions 1.4 and 2.3 of apgdiff.

This issue must be similar with the one in the report n°3511565 (Comment on Inherited column Exception). If I had to guess what we're dealing with, I'll say apgdiff only memorise an inherited column as a link/pointer when Postgresql actually memorise a new set of properties in addition.

**Comment by DemonVex** [comment]
PR #117
